### ISSUE TITLE
eXtremely Duplicated iSsue Discrepancy (XDSD)

### ISSUE THREAD

**Issue by maurezen** [teamed/xdsd#12]
Have recently stumbled upon the following issue.

Imagine a project consisting of a multiple modules in a hierarchical dependency structure. Under the current project architecture if an issue is found in the module H high in the hierarchy, it is reported, gets fixed, and the new version of the module H is released. 

Now, under current architecture, to propagate the fix, one should update each of the descendants of H, say, d1 .. dn, to depend on (or use) the new version of H, which seems to call to n submitted issues. 

That's where the problem starts: this is actually the same issue, which, due to the project architecture, gets multiplied n-fold, leading to a significant expense due to the one issue. Moreover, there is no guarantee that the similar issue won't arise in the future (to the contrary, it most assuredly would).

While paying through the nose for the bug fix doesn't look good, neither does not fixing the bug if it is actually there, neither does not reporting the bug if it actually there. 

What would an XDSD professional recommend?

**Comment by maurezen** [comment]
@yegor256 any comments?

**Comment by yegor256** [comment]
@maurezen good question, not sure I have an answer at the moment. We'll think about it. Thanks.

**Comment by maurezen** [comment]
@yegor256 when will it be appropriate to ping you about updates on the matter?

**Comment by yegor256** [comment]
@maurezen I think I have an answer now. We recently updated our policy, see [par.13](http://www.teamed.io/policy.html#13). So, it's up to the project architect - what to do with bugs. If he/she thinks that they add value to each subsidiary project, he/she will accept them, even though they may look duplicate. However, if he/she thinks that duplicate bugs won't give enough value to the project(s), they won't be accepted and won't go through a full bug processing flow. So, it's subjective.

**Comment by maurezen** [comment]
@yegor256 So if the duplicates are actually a big enough bug, everyone gets paid in full, and if they are a minor defect, nobody does - and the defect doesn't get fixed, right?

**Comment by yegor256** [comment]
@maurezen yes, more or less like that. But not exactly. Even a minor defect may be valuable sometimes, when the architect thinks so. It all depends on the goals of the project. We all work for the project and our goal is to please the project (see http://www.yegor256.com/2015/01/26/happy-boss-false-objective.html). If the project is a development of a private software to be shipped in a few weeks and installed somewhere, it's not important that it doesn't build on Mac OS, if all developers are on Linux. So the architect will simply decline such a bug. But, on the other hand, if we're developing some open source component that is supposed to be maintained by the public, such a bug would be much more serious. So, it's subjective.
