### ISSUE TITLE
Who gets paid for puzzles?

### ISSUE THREAD

**Issue by maurezen** [teamed/xdsd#14]
As far as I understand XDSD promotes PDD as the main method of coping with the large tasks. 

This leads to a question: when the issue being a request for puzzle resolution gets submitted to the issue tracker, who should get paid for it?

**Comment by maurezen** [comment]
@yegor256 any comments?

**Comment by yegor256** [comment]
@maurezen none of programmers, since this issue/bug is organically coming from an existing code base. There is no point in compensating a developer for this.
