### ISSUE TITLE
Will XDSD work for office?

### ISSUE THREAD

**Issue by atapin** [teamed/xdsd#18]
E.g., XDSD states that one must not use informal ways of communication. This is almost impossible in office, where employees can talk directly to each other. Of course, this is normal for people, but often can be very distractive. 
Are there any examples of applying the technique in office environments?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@atapin I think it can work in an office environment (I've never tried), but will need very mature and professional participants. Basically, they will be strong enough to say "shut up, I'm not interested in talking to you, make a ticket". Only a true professional will be ready to accept that without getting offended.

**Comment by atapin** [comment]
@yegor256 thanks for the answer
