### ISSUE TITLE
award 2015

### ISSUE THREAD

**Issue by yegor256** [teamed/xdsd#21]

**Comment by davvd** [comment]
@yegor256 this is yours, pls go ahead

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-4fca0d17

**Comment by yegor256** [comment]
@davvd please add extra 23 hours to @longtimeago for 92 contest projects reviewed

**Comment by yegor256** [comment]
@davvd please add 450 minutes to @krzyk for 30 projects reviewed

**Comment by yegor256** [comment]
@davvd please add 405 minutes to @carlosmiranda for 27 projects reviewed

**Comment by davvd** [comment]
> @davvd please add extra 23 hours to @longtimeago for 92 contest projects reviewed

@yegor256 I've paid 23 hours to @longtimeago in transaction `67498966`

**Comment by davvd** [comment]
> @davvd please add 450 minutes to @krzyk for 30 projects reviewed

@yegor256 I've sent 7 hours and 30 mins extra to @krzyk in transaction ID "67500305"

**Comment by davvd** [comment]
> @davvd please add 405 minutes to @carlosmiranda for 27 projects reviewed

@yegor256 I've paid 6 hours and 45 mins to @carlosmiranda in transaction `67500310`

**Comment by yegor256** [comment]
@krzyk @carlosmiranda @longtimeago thanks all!

**Comment by carlosmiranda** [comment]
@yegor256 thanks!

**Comment by davvd** [comment]
@yegor256 Thanks so much! Your account was topped up for **45 mins** (transaction ID is `000-9e812674`, the task took 47 hours and 32 mins); the bonus for fast delivery (m=2852); +45 added to your rating, current score is: [+12415](http://www.netbout.com/b/35008?open=rating)
