### ISSUE TITLE
a skill attribute for tasks

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/xdsd#22]
Right now a developer have a choice to be member of a project or not. It works good for projects of single technology. But if project has mixed technology stack like IOS frontend and java backend, a developer will be assigned to random task. No matter he/she has needed skills or not. A developer has to reject unacceptable tasks. The developer will lose points, the project will require more time to complete the tasks.
I propose make more granular assignment. Any task must has a skill attribute like IOS, JAVA, Android, Angular, Hadoop, etc. Any developer have to inform  about available skills. So the assignment should take into account a developer skills.
The architect of the project can ask to set skill attribute of the task. Also a default skill for the project has to  be.

**Comment by yegor256** [comment]
@dmzaytsev it sounds logical, but I have a better idea - we just have to do one technology per Github repo. In other words, we should NOT have repositories with mixed tech stacks. That will solve the problem more organically.
