### ISSUE TITLE
current project roles

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/xdsd#23]
Right now we don't know exactly who is who in a project.
It would be good to know current project roles.
something like this

Role|Github account
------|--------------------
`@karato`|Project manager
`@yegor256`|Architect
...|System analyst
...|...

It may be a link in Readme to a wiki page.

**Comment by yegor256** [comment]
@dmzaytsev good point, thanks

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `68295337`

**Comment by yegor256** [comment]
@dmzaytsev it works already, for example: https://github.com/teamed/proday-api/blob/master/TEAM.md

**Comment by dmzaytsev** [comment]
@yegor256 perfect, thanks!

**Comment by dmzaytsev** [comment]
@yegor256 btw, there isn't PM role in that table

**Comment by yegor256** [comment]
@dmzaytsev aha, I'll fix that

**Comment by dmzaytsev** [comment]
@yegor256 also it would be good add roles description or a link, to get rid questions like "SA is software architect or system analyst"

**Comment by yegor256** [comment]
@dmzaytsev yeah, good idea, thanks
