### ISSUE TITLE
PM doesn't reassign a task

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/xdsd#24]
Sometimes project manager doesn't reassign a task when the time limit exceeded.
For example this task https://github.com/yegor256/netbout/issues/737 has been assigned Oct 22 but still in progress state yet.
It looks as a bug of PM's automation tools to me

**Comment by yegor256** [comment]
@dmzaytsev this is not a bug, but a feature. If there are no more programmers in the project, there is no reason to re-assign. When new people will join the project, this task will be re-assigned.
