### ISSUE TITLE
Common repository for IDEA configuration

### ISSUE THREAD

**Issue by alexey-krylov** [teamed/xdsd#27]
IDEA has default option called 'Settings Repository' (https://github.com/develar/settings-repository plugin).
It allows to sync IDEA codestyle/inspections configuration between team members.
We can create teamed.io special repo for configs. This will significantly reduce codestyle frustration.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@alexey-krylov not a bad idea, but we don't see Teamed.io as a group of developers. We're a management company. In each project programmers may have different configuration and different coding styles. If you want to use my settings, get them here: http://www.yegor256.com/about-me.html

**Comment by alexey-krylov** [comment]
@yegor256 can you share latest version of settings?

**Comment by yegor256** [comment]
@alexey-krylov just uploaded the current version I'm using now

**Comment by alexey-krylov** [comment]
@yegor256 thanks, tested this version and i'm still in frustration. When i do 'Reformat code' with IDEA produced results still can't pass codestyle checks. It seems it's impossible to setup IDEA to do reformat in accordance to Qulice rules.
Is this a usual situation with Qulice when you can't rely on automatic code reformat and have to check every single line manually?

**Comment by yegor256** [comment]
@alexey-krylov don't use auto-formatting, it's for newbies :) format code manually, that's how you structure it right and structure your mindset
