### ISSUE TITLE
Scrutinizer PHP checks

### ISSUE THREAD

**Issue by alexey-krylov** [teamed/xdsd#29]
Why Scrutinizer do PHP checks when projects mostly in Java?
This check is very long and take a lot of time.

I offer to disable them totally or by per-project basis (i don't know, maybe there is hidden teamed.io PHP projects)

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@alexey-krylov I don't understand what you're talking about... what PHP has to do with this project? I'm closing.

**Comment by alexey-krylov** [comment]
@yegor256 When user creates pull request set of code quality checks started. One of them is Scrutinizer. This tool performs complete code analysis including Java-related checks and PHP-checks. To see that you need to open Scrutinizer during its work. I don't understand why PHP-checks performed on java projects. IMO they needs to be disabled.

**Comment by yegor256** [comment]
@alexey-krylov where exactly this is happening? in which project?

**Comment by alexey-krylov** [comment]
@yegor256 i saw this in 'Takes'

**Comment by alexey-krylov** [comment]
![sshot-1](https://cloud.githubusercontent.com/assets/953840/12594980/c7483d28-c489-11e5-9b70-8cc923abf8f2.png)
see 'PHP Analyzer: Determining Dependencies'. This takes more than minute
https://scrutinizer-ci.com/g/yegor256/takes/inspections/0b3a5ca1-1348-4ac1-8f82-780e458fdb48

**Comment by yegor256** [comment]
@alexey-krylov why did you report it here? report it in Takes
