### ISSUE TITLE
XDSD Definition of Done is not clear

### ISSUE THREAD

**Issue by mkordas** [teamed/xdsd#39]
There's DoD at http://www.yegor256.com/2014/04/15/definition-of-done.html. The following things are not clear for me in it:
>Ask about payment if you don’t receive it automatically after an author closes your task(s)

Who should be asked about payment?

> Stay after the author to close tasks — be aggressive

What if author of the task is not active on GitHub anymore or doesn't have any interest in closing it? What is the way of escalating such situation?
Moreover, what if author of a task is PM? Does it make sense to chase PMs to close tasks?

> Every task has its own time budget. Regardless of the number of people who worked on a task previously, only the last one — the one who managed to provide a working deliverable

What if two people were working on a task and both provided a working deliverables?

> Combining the definition of done and the principle of paying only for deliverables provides us a very important conclusion: we do not pay for un-finished tasks.

OK, but what does it mean that e.g. code review is done?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@mkordas I made some changes, see https://github.com/yegor256/blog/commit/69a2e31b55c575016c053151035460e3c8fd04ba other questions are not valid. we never have two people working on the same task. and code review is done when ticket is closed/merged.

**Comment by mkordas** [comment]
@yegor256 thanks for the fixes, but the following questions remain for me open:
> Does it make sense to chase PMs to close tasks?

I was chasing PMs to close tasks several times and it wasn't helpful, I was even told not to do that as it won't speed up anything. Should I continue to chase them?

> What if author of the task is not active on GitHub anymore or doesn't have any interest in closing it? What is the way of escalating such situation?

Did I understand correctly - there's nothing that can be done except being aggressive to the ticket author and in worst case task will be open indefinitely?

> What if two people were working on a task and both provided a working deliverables?

I meant that I can imagine situation where first person manages to merge solution, but then ticket author is not happy, another person takes over and finishes. In that case only second person gets payment, right?
The nuance here is to state that not only "deliverable" counts, it's the person who fulfils entire DoD including issue closure.
