### ISSUE TITLE
Links using xdxd.org stopped working

### ISSUE THREAD

**Issue by mkordas** [teamed/xdsd#41]
Recently many links using xdsd.org domain stopped working. E.g. http://www.xdsd.org/2014/04/20/how-hourly-rate-is-calculated.html was working fine a few days ago while right now it gives 404.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mkordas fixed already, thanks
