### ISSUE TITLE
Tasks with impediments should not block

### ISSUE THREAD

**Issue by CarlosGines** [teamed/xdsd#44]
A task assigned to a developer might have an impediment that needs to be resolved before solving the original task. This can take a undetermined amount of time: days, weeks or months. And during this time, the developer has 1 of the slots from his/her concurrent tasks limit taken. This has a negative impact the score of the developer.

If my concurrent tasks limit is 2, and I have assigned 1 task that has an impediment, I will only be able to work on 1 task at the same time for I don't know how long. If a have an impediment on another task, I could get completely stuck until the impediments disappear.

This is a waste of time and and a obstacle for the developer to keep working. Tasks with an impediment should not be taken into account for the concurrent tasks limit.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@CarlosGines I totally understand what you're coming from, but if we do what you're suggesting, new developers will abuse that and mark most of their tasks as "impeded", just to get new tasks. thus, I would recommend you (until your limit is still low) don't put your tasks on hold. instead, un-assign yourself from them and get new tasks. when your limit will be high enough, you will have the luxury to have some tasks on hold.

**Comment by CarlosGines** [comment]
@yegor256 is it possible to abuse it? I mean, impediments have to be accepted by the project manager, they need to exist, you cannot invent them. 

It doesn't feel right for me to be docked points for a reason that is external to me, such as being assigned to a task that has an external impediment.
