### ISSUE TITLE
Assignee's speed of delivery and task management speed

### ISSUE THREAD

**Issue by amihaiemil** [teamed/xdsd#46]
Currently the speed of delivery is calculated in days from the moment a task is assigned, until the moment it is closed.

I think it should be calculated from the assignment date until the **last** PR is merged. 
Because it often happens that the PR is merged in x days and then the task waits another x days for the PM/author/reviewer to answer and/or deploy the PR and close the issue. 

This way, the developer's rating is not affected by the work schedule of the issue author, PM etc.  

**E.g.** PR https://github.com/jcabi/jcabi-dynamo/pull/74 was merged in 4 days, but the corresponding issue. https://github.com/jcabi/jcabi-dynamo/issues/65 was finally closed in 8 days, with nothing for the developer to do about it. 

I have other examples as well... It's a general sitiuation, form my point of view, that the issue management and/or coordination lasts considerably longer than the task itself.

It says in the documentation that the developer should be "aggressive" and spam the people with messages. I find that useless. The developer will ping them once or twice, but what more can he do? 
Maybe the other person has a good reason for the delay. And if they don't and it's just laziness, then again, spamming and pinging makes no difference.

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@amihaiemil we can't pay attention to PRs. there could be many PRs and some of them are good, some not. we need to be very explicit and strict. that's why, when it's closed, it's done. no matter what happened inside.
