### ISSUE TITLE
What are the statements that the PM understands?

### ISSUE THREAD

**Issue by amihaiemil** [teamed/xdsd#48]
What are the exact statements that the PMs can understand from a DEV? They receive a lot of addressed messages and answer to very few of them. In general I noticed that only "need more time" is answered properly. 

For instance, can I tell the PM to assign a task to me, if I am not the reporter? I simply see a task that I would like to do and want the PM to assign it to me. Is that possible?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
