### ISSUE TITLE
PM should take ownership of certain tasks

### ISSUE THREAD

**Issue by amihaiemil** [teamed/xdsd#49]
If a task is reported by someone which is not in the project's team, or if the author leaves the team after submitting a task, the PM should take ownership of it.

The 2 scenarios are: 

1) Someone out of the team reports an issue/asks for enhancements etc. Once it is accepted, why can't the PM take ownership? It will be implemented how we think best, coordinated by CR and architect. The current argument against this is that the author decides if a task is well implemented or not. But does the author care in this instance? No - they do not. They either ask for a fix, or ask for new feature. We fix it and there is no more to discuss, or we implement a new feature and let them know how to use it.

2) Someone from our team reports an issue and then leaves the team before it is closed. Same as above. 

The biggest argument towards this approach is that an author can report an issue and never close it. Maybe because he does not want to, maybe because he simply switched off notifications from that issue months/years ago and does not even know what's going on anymore... 

Like [this](https://www.google.com/url?hl=en-GB&q=https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/3%23issuecomment-241344114&source=gmail&ust=1471941121454000&usg=AFQjCNEQV5-GLHC4D3wrh4xREHwfi6DqPg) for instance... it was opened 2 years ago, no one can reproduce it (honestly, I believe he simply ran out of RAM at the moment) and the author does not want to close it. I even contacted him directly by email asking for this. 

In the end I rejected the task and of course my rating was deducted. In turn, this ghost task will keep being passed from dev to dev indefinetly.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
