### ISSUE TITLE
Flexible max number of tasks?

### ISSUE THREAD

**Issue by amihaiemil** [teamed/xdsd#50]
Currently there is a max number of tasks a dev can receive, according to the rating. 
Wouldn't it be better if the developer said how many tasks he can handle concurrently? 

I don't find the rating a good measurement for this topic (Currently the more points you have, the more tasks you can get, I know). 

But here's the problem. From the time I get a ticket and until it is closed, I spend 25-30% of the whole time on the initial PR. The rest of the time goes on waiting for other people involved in the ticket, and another few part goes in CR changes/fixes - very rarely it happened otherwise. 

The point is that you have a developer with 5 tasks max, and most of the time while those 5 slots are occupied, he just waits for reivewing and feedback. This is a waste of time and loss for both the dev (he loses time and money) and the project (loses resources, the dev stays idle). 

Of course, you cannot take out the task limit, but the developer could tell you how much he can take? Myself, right now, I have 7 tasks and still, **most of the time** I'm waiting for others to do their part so I can close the ticket. I even let tickets go, since they took too much time, kept a slot occupied which otherwise could have been "productive"

**Comment by amihaiemil** [comment]
I also understand there is a budget to take care of and often tasks halt and cannot be assigned because of that, but it is not necessary to always assign the most number of tasks to a developer. 

Maybe I have 15 max tasks and it's not affordable at the moment, there is a budget gap or whatever: it's not necessary to assign me 15 tasks, less would do. 

So it's all about possibilities. If the project can afford it and the dev has the time, why not go with it?

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
