### ISSUE TITLE
Typo in the whitepaper

### ISSUE THREAD

**Issue by Glusk2** [teamed/xdsd#52]
There's a typo in https://github.com/teamed/xdsd/blob/master/pdf/XDSD-WhitePaper.pdf

Page 4, section **What History Says**, first sentence:

> Since **the**1960**<del>x</del>s**, when software engineering as an
> independent profession was born, the success factors of
> software projects concerned their sponsors.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@Glusk2 fixed in 	3efe775 thanks!
